"""Bilingual quick guides using the exact native tutorial text."""
from pathlib import Path
import ast,html,json,sys
BASE=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(BASE))
from off.templates import make_template
tree=ast.parse((BASE/'off/quickstart.py').read_text(encoding='utf-8'))
node=next(n.value for n in ast.walk(tree) if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='topics' for t in n.targets))
pairs=list(node.elts)
for call in ast.walk(tree):
    if isinstance(call,ast.Call) and isinstance(call.func,ast.Attribute) and isinstance(call.func.value,ast.Name) and call.func.value.id=='topics' and call.func.attr=='append':pairs.append(call.args[0])
topics=[[(ast.literal_eval(call.args[0]),ast.literal_eval(call.args[1])) for call in pair.elts] for pair in pairs]
names=[('cylinder3d','3D circular cylinder','三维圆柱'),('cylinder2d','2D circular cylinder','二维圆柱'),('square','Square bluff body','方柱钝体'),('triangle','Triangular bluff body','三角形钝体'),('tandem','Tandem cylinders','串列双圆柱'),('polygon','Polygon bluff body','多边形钝体'),('box','Uniform rectangular through-flow','均匀矩形穿流')]
css='body{font:16px/1.7 "Segoe UI","Microsoft YaHei",sans-serif;color:#19344f;margin:0;background:#eef2f5}header{background:#183b59;color:white;padding:32px 6vw}main{max-width:1050px;margin:auto;padding:24px}section{background:white;padding:24px;margin:20px 0;border:1px solid #cad6df}h2{color:#17687a}table{border-collapse:collapse;width:100%;font-size:14px}td,th{border:1px solid #ced9e2;padding:10px;text-align:left}pre{background:#edf2f6;padding:16px;white-space:pre-wrap;overflow-wrap:anywhere}a{color:#087d98}.note{border-left:4px solid #ca931a;padding:14px;background:#fff5df}nav{background:white;padding:12px 6vw}code{font-family:Consolas,monospace}@media print{body{background:white}}'
docs=BASE/'docs'; docs.mkdir(exist_ok=True)
for lang,index in [('EN',0),('ZH',1)]:
    def t(en,zh): return zh if index else en
    rows=[]
    for key,en,zh in names:
        p=make_template(key)
        rows.append('<tr>'+''.join('<td>'+html.escape(str(v))+'</td>' for v in [zh if index else en,f'{p.dimension}D',p.mesh_method,f'x=[{p.xmin},{p.xmax}], y=[{p.ymin},{p.ymax}] m',len(p.shapes)])+'</tr>')
    sections=['<section><h2>'+t('Start here','从这里开始')+'</h2><p>'+t('Launch the latest desktop shortcut. Settings selects English or Chinese. Choose Preprocessing at the bottom stage tabs, then Design or Meshing in the viewport header. The left tree selects the same objects; it does not create a second mesh.','使用最新桌面快捷方式启动，设置里切换中英文。底部流程选前处理，再用视口上方的设计/网格页签；左侧树选择同一套对象，不会另外生成第二份网格。')+'</p><p class="note">'+t('Planar solid drawing and 3D extrusion are implemented. Manual planar node/curve/region topology editing is available; arbitrary 3D CAD assemblies are not implemented. Straight open lines do not become a solid wall.','已实现平面实体绘制与三维拉伸；新增手动平面节点/曲线/区域拓扑编辑，尚未实现任意三维 CAD 装配。开放直线不会自动变成实体壁面。')+'</p></section>']
    for number,pair in enumerate(topics,1):
        sections.append(f'<section id="tutorial-{number}"><h2>'+html.escape(pair[0][index])+'</h2><p>'+html.escape(pair[1][index])+'</p></section>')
    sections.append('<section id="starters"><h2>'+t('Seven starters — Project menu','七个典型模板 — 项目菜单')+'</h2><table><tr>'+''.join('<th>'+v+'</th>' for v in [t('Starter','模板'),t('Dimension','维度'),t('Backend','后端'),t('Domain','流场'),t('Bodies','实体数')])+'</tr>'+''.join(rows)+'</table><p>'+t('These are starter configurations, not verified benchmark solutions. Default endTime=10 s, maximum internal step=0.005 s, saved interval=0.5 s; edit these for your problem. Multiple bodies share the cylinder wall patch and collective force. The box has uniform through-flow boundaries, not no-slip channel walls.','这些是起点配置，不是已验证基准解。默认 endTime=10 s、最大内部步长=0.005 s、保存间隔=0.5 s，应按问题调整。多个实体共用 cylinder 壁面和总力，空盒为均匀穿流边界，不是无滑移通道。')+'</p></section>')
    sections.append('<section id="backend"><h2>'+t('What is actually executed','实际执行什么')+'</h2><pre>Structured cylinder O-grid / partitioned box:\nsystem/blockMeshDict → blockMesh → constant/polyMesh\n\nGmsh triangle/prism, quad-dominant, tetrahedral:\noff/mesh.py::build_gmsh → geometry.msh\ngmshToFoam geometry.msh → constant/polyMesh\ngeometry.brep = CAD geometry, not the mesh\n\ncheckMesh -allGeometry -allTopology\ndecomposePar → mpirun -np &lt;cores&gt; foamRun -parallel</pre><p>'+t('Gmsh 3D planar extrusion does not mean fully arbitrary CAD. Quad-dominant mode may retain triangles/prisms. Both backends require quality checks before solver submission.','Gmsh 三维平面拉伸不代表任意 CAD，四边形主导模式仍可能有三角形/棱柱。两个后端均须通过质量检查后提交求解。')+'</p></section>')
    sections.append('<section id="files"><h2>'+t('Complete file map','完整文件对应关系')+'</h2><pre>off_project.json                  SI project parameters\nmesh_backend.json                selected backend and draft status\nmesh_generator_source.py         mesh generator source snapshot\n0/U, 0/p, 0/&lt;model fields&gt;        initial and boundary fields\nconstant/physicalProperties      viscosity\nconstant/momentumTransport       laminar / RAS / LES model\nsystem/controlDict               time, saved interval, functions\nsystem/fvSchemes                 discretisation\nsystem/fvSolution                solvers and PIMPLE\nsystem/decomposeParDict          actual MPI decomposition\nsystem/blockMeshDict             structured mesh input\ngeometry.msh / geometry.brep      Gmsh mesh / CAD input\nconstant/polyMesh/*              actual converted/generated mesh\nprocessor*/&lt;time&gt;/*              genuine parallel fields\nlog.mesh, log.checkMesh, log.solver actual execution evidence</pre><p>'+t('Files → Generated design files creates a draft from the current project; editable recognised OpenFOAM dictionaries apply explicit project overrides when saved. Files → Selected case files shows the queue selection read-only. Files → OpenFOAM run directory exposes all existing WSL cases, including previous versions, without queue selection. Files → Application source exposes the entire application folder read-only. Text over 2 MB and binaries show metadata. A draft is neither checkMesh approval nor a solved case.','文件 → 生成设计文件按当前项目生成草稿；可编辑的 OpenFOAM 字典保存后成为明确的项目覆盖。文件 → 所选算例文件只读显示当前队列选项；文件 → OpenFOAM 算例目录可查看包括旧版在内的全部 WSL 算例，不必先选队列。文件 → 软件源码只读显示整个软件目录。超过 2 MB 的文本和二进制显示元数据。草稿不是 checkMesh 通过证据，也不是计算完成的算例。')+'</p></section>')
    sections.append('<section><h2>'+t('References','参考资料')+'</h2><p><a href="https://doc.cfd.direct/openfoam/user-guide-v14/blockmesh">OpenFOAM Foundation 14 — blockMesh user guide</a><br><a href="https://gmsh.info/doc/texinfo/">Gmsh — official reference manual</a><br><a href="http://spaceaero.space">spaceaero.space — project help website</a></p><p>'+t('Software by zongxuan and hanwen. Current fresh tests and retained prior tests are identified in the full manual and evidence reports.','作者 zongxuan 和 hanwen。本版新测试与保留的历史测试在完整手册和证据报告中分别标注。')+'</p></section>')
    document=f'<!doctype html><html lang="{ "zh-CN" if index else "en"}"><meta charset="utf-8"><title>Open Foam Friend 0.15 Quickstart {lang}</title><style>{css}</style><header><h1>Open Foam Friend 0.15</h1><p>'+t('Drawing, meshing and actual file access','绘制、网格与真实文件访问')+'</p></header><nav><a href="manual_'+lang+'.html">'+t('Full manual','完整手册')+'</a></nav><main>'+''.join(sections)+'</main></html>'
    (docs/f'quickstart_{lang}.html').write_text(document,encoding='utf-8')
print('Bilingual quick guides generated from native tutorial strings.')
