"""Build reproducible, app-local Windows bundles. No recipient pip/downloads."""
import sys,json,shutil,hashlib,time,zipfile,html
from pathlib import Path
BASE=Path(__file__).resolve().parents[1];ROOT=BASE.parent;CACHE=ROOT/'installer_cache';DIST=ROOT/'packages'/BASE.name
def digest(path):
    with path.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def manifest(folder):
    files={p.relative_to(folder).as_posix():digest(p) for p in sorted(folder.rglob('*')) if p.is_file() and p.name!='bundle_manifest.json' and '__pycache__' not in p.parts}
    (folder/'bundle_manifest.json').write_text(json.dumps(dict(release=BASE.name,sha256=files),indent=2),encoding='utf-8')
def guide(lang):
    zh=lang=='ZH'
    content='''<h1>Open Foam Friend 0.17.0 · 离线安装说明</h1><p>作者：zongxuan &amp; hanwen。Windows x64 软件；欢迎页和安装器均可选择中文 / English。</p>
<h2>选择哪个包</h2><table><tr><th>包</th><th>自带 Windows 环境</th><th>WSL / OpenFOAM</th></tr><tr><td>FULL 完整包</td><td>Python 3.12.10、Qt/PySide6 6.11.2、VTK 9.6.2、Gmsh 4.15.2、NumPy/SciPy 等</td><td>Microsoft WSL 2.7.14 MSI + 干净 Ubuntu 24.04 镜像：OpenFOAM Foundation 14、MPI 4.1.6、Linux Gmsh 4.12.1</td></tr><tr><td>LITE 简易包</td><td>相同，电脑不用安装 Python</td><td>只读检查；缺少时显示错误。不会启用 Windows 功能、安装 MSI、导入 Linux 或执行 apt/pip。</td></tr></table>
<h2>对方第一次使用完整包</h2><ol><li>把整个 ZIP 复制过去，解压到本地可写目录，不能直接在 ZIP 里面运行。至少预留 10 GB，建议 15 GB 以上。Windows 10 build 19041 或更新版本 / Windows 11，Intel/AMD x64；本包不支持 ARM64。CPU 虚拟化必须在 BIOS/UEFI 启用。</li><li>双击 <code>Setup.cmd</code>，上方选择语言。点击“1 · 准备 Windows / WSL”，接受 UAC 管理员授权。它使用本地 Microsoft MSI，启用所需 Windows 功能，不下载个人发行版。</li><li>若提示重启，保存工作后自行重启。安装器不会强制重启。重启后重新双击同一个 <code>Setup.cmd</code>。</li><li>以普通用户点击“2 · 安装软件与 Linux 镜像”，选择空目录。默认发行版 <code>OpenFoamFriend-14</code>，默认普通用户 <code>off</code>。同名非本软件发行版、非空陌生目录受到保护。可改专用发行版名称。</li><li>安装完成后点“启动”，或使用桌面 / 开始菜单的 Open Foam Friend 快捷方式。欢迎页右上角直接切换中文 / English。WSL 配置与软件安装会自动连好；已有配置先备份。</li></ol>
<h2>简易包</h2><p>解压后双击 <code>Start Portable.cmd</code> 可直接运行，不必安装。也可用 <code>Setup.cmd</code> 安装本软件与快捷方式。用 <code>Check Environment.cmd</code> 只读诊断；缺少环境退出码为 2。没有 OpenFOAM 时可设计几何、预览网格和编辑代码，提交求解需要你已有的 OpenFOAM Foundation 14 环境。进入 WSL 配置自动探测 / 手工指定发行版、bashrc、算例目录。</p>
<h2>计算与文件位置</h2><p>完整包 Linux 算例目录 <code>/home/off/OpenFOAM/off14/run</code>；资源管理器可用 <code>\\\\wsl.localhost\\OpenFoamFriend-14\\home\\off\\OpenFOAM\\off14\\run</code>。修改发行版名称后替换该段。Python 在安装目录的 <code>runtime</code> 中，软件源代码和双语使用手册在版本目录。配置位于 <code>%APPDATA%\\OpenFoamFriend</code>。SSH 连接远端还需要你自己的主机名、账号和密钥，不包含任何凭据。</p>
<h2>故障处理</h2><ul><li>启动没反应：用 <code>Start Console.cmd</code>，保留错误；切勿只复制一个启动文件。</li><li>WSL 0x80370102：检查 BIOS 虚拟化、VirtualMachinePlatform，重启后重试；虚拟机内部运行还需要嵌套虚拟化。</li><li>公司策略禁止 WSL / 无管理员权限：完整包无法绕过策略。联系管理员，或用简易包连接已有环境 / SSH 服务器。</li><li>安装器长时间工作：进度条和日志持续显示阶段；首次镜像导入可能需数分钟，不要强制关闭导入。</li><li>换电脑不要搬旧队列数据库；项目文件可复制，机器 WSL 路径需重新探测。安装包不带任何个人科研算例、账号、SSH 密钥。</li></ul>
<h2>验证范围与限制</h2><p>本次实际验证结果见 <a href="package_verification.html">安装包验证记录</a>。安装包包含完整软件源代码，不把历史仿真数据作为本次验证。当前主机已启用 WSL，因此“完全未启用 WSL 的陌生电脑 → UAC → BIOS → 重启”的全过程没有物理实机验证，不能承诺所有电脑一次成功。没有外置 ParaView；软件使用自带 VTK 查看与导出，.foam 可另用 ParaView 打开。短时间三维测试验证工作流，不证明圆柱流场物理统计收敛。</p>'''
    if not zh:content='''<h1>Open Foam Friend 0.17.0 · Offline installation</h1><p>Authors: zongxuan &amp; hanwen. Select Chinese / English directly in the installer and welcome page.</p>
<h2>Choose a package</h2><table><tr><th>Package</th><th>Windows runtime included</th><th>Linux solver environment</th></tr><tr><td>FULL</td><td>Python 3.12.10, Qt/PySide6 6.11.2, VTK 9.6.2, Gmsh 4.15.2, NumPy, SciPy and dependencies</td><td>Microsoft WSL 2.7.14 MSI + clean Ubuntu 24.04 image with OpenFOAM Foundation 14, MPI 4.1.6, Linux Gmsh 4.12.1</td></tr><tr><td>LITE</td><td>Same app-local runtime; no system Python required</td><td>Read-only detection and errors only. No MSI, Windows feature changes, Linux import, apt or pip.</td></tr></table>
<h2>FULL on a new computer</h2><ol><li>Copy the entire ZIP and extract to a writable local folder. Never run inside the ZIP. Reserve at least 10 GB, preferably 15 GB+. Windows 10 build 19041+ / Windows 11, Intel/AMD x64 only. ARM64 is not supported. Enable CPU virtualization in BIOS/UEFI.</li><li>Open <code>Setup.cmd</code>. Select the language. Click “1 · Prepare Windows / WSL” and approve administrator UAC. The bundled Microsoft MSI and Windows features are used.</li><li>If a restart is requested, save work and restart manually. No automatic reboot. Open the same <code>Setup.cmd</code> afterwards.</li><li>As the ordinary user, select an empty installation directory and click “2 · Install complete software + Linux image”. Default dedicated distribution: <code>OpenFoamFriend-14</code>, unprivileged Linux user: <code>off</code>. Existing unrelated distributions and nonempty unmanaged directories are protected. Change the dedicated distribution name if needed.</li><li>Click Start, or use the desktop / Start Menu shortcut. The welcome page has a live Chinese / English selector. WSL settings are configured automatically; existing settings are backed up.</li></ol>
<h2>LITE</h2><p>Open <code>Start Portable.cmd</code> after extraction, or use <code>Setup.cmd</code> for app installation and shortcuts. <code>Check Environment.cmd</code> only diagnoses; missing solver environment returns exit code 2. Geometry, mesh design and code editing remain available without OpenFOAM. Solving requires an existing OpenFOAM Foundation 14 environment; use WSL discovery or configure distribution, bashrc and case path.</p>
<h2>Files and administration</h2><p>FULL case directory: <code>/home/off/OpenFOAM/off14/run</code>; Explorer: <code>\\\\wsl.localhost\\OpenFoamFriend-14\\home\\off\\OpenFOAM\\off14\\run</code>. Substitute the distribution name if changed. The runtime is in <code>runtime</code>, app source/manuals in the version folder, settings in <code>%APPDATA%\\OpenFoamFriend</code>. SSH requires your own hostname, credentials and keys; none are bundled.</p>
<h2>Troubleshooting</h2><ul><li>No visible startup: use <code>Start Console.cmd</code> and retain the error. Do not copy a launcher alone.</li><li>WSL 0x80370102: check BIOS virtualization and VirtualMachinePlatform; restart. Virtual machines require nested virtualization.</li><li>Corporate policy / no admin rights: the package cannot bypass policy; contact your administrator or use LITE with an existing environment / SSH server.</li><li>Import takes minutes: watch the progress bar and log; do not forcibly close an active import.</li><li>Move project files, not another computer’s queue database. Rediscover machine paths. No personal research cases, accounts or SSH keys are included.</li></ul>
<h2>Validation and limits</h2><p>See <a href="package_verification.html">package verification</a>. Source is included. The host already supports WSL; a physical cold Windows machine, BIOS changes, UAC and reboot sequence have not been tested end to end. This is not a claim of universal hardware compatibility. External ParaView is not bundled; the app provides VTK viewing/export, and .foam can be opened in separately installed ParaView. Short 3D runs validate the workflow, not statistically converged cylinder physics.</p>'''
    content+=('<h2>其他自带组件与系统边界</h2><p>另含离线 OpenSSH 客户端（Microsoft 上游 10.0.0.0p2-Preview，版本标识为上游预览版）；不会安装 SSH 服务器或服务。超算需要你自己的账号、密钥、网络与远端 Slurm/OpenFOAM，本次没有真实集群账号，未验证远端端到端提交。Windows 功能启用禁止自动下载修复文件；若操作系统组件存储缺失或损坏，需要管理员用对应 Windows 安装介质修复，安装包不包含 Windows 操作系统。</p>' if zh else '<h2>Additional bundled components and system boundary</h2><p>An offline OpenSSH client is included (Microsoft upstream 10.0.0.0p2-Preview, explicitly an upstream preview version). No SSH server or service is installed. Cluster credentials, keys, network access and remote Slurm/OpenFOAM are site-specific; no real cluster account was available for end-to-end remote submission testing. Windows feature enablement prohibits automatic repair downloads. A missing/corrupt OS component store requires an administrator and matching Windows installation media; the Windows operating system is not bundled.</p>')
    content+='''<h2>Official references / 官方依据</h2><p><a href="https://learn.microsoft.com/en-us/windows/wsl/install">Microsoft WSL installation / offline instructions</a> · <a href="https://learn.microsoft.com/en-us/windows/wsl/basic-commands">WSL import/export</a> · <a href="https://openfoam.org/download/14-ubuntu/">OpenFOAM 14 Ubuntu installation</a> · <a href="https://docs.python.org/3.12/using/windows.html#the-embeddable-package">Python embedded runtime</a> · <a href="https://github.com/PowerShell/Win32-OpenSSH/releases/tag/10.0.0.0p2-Preview">Bundled SSH provenance</a></p><p><a href="../application/'''+BASE.name+'''/docs/manual_'''+lang+'''.html">Full software manual / 完整软件使用手册</a> · <a href="http://spaceaero.space">spaceaero.space — help / 帮助</a></p>'''
    return '<!doctype html><html lang="'+('zh-CN' if zh else 'en')+'"><meta charset="utf-8"><title>Open Foam Friend Installation</title><style>body{font:16px/1.6 Segoe UI,Arial,sans-serif;max-width:1040px;margin:40px auto;padding:0 24px;color:#203c50}h1,h2{color:#173b5d}table{border-collapse:collapse;width:100%}td,th{padding:12px;border:1px solid #b8cad8;text-align:left}th{background:#edf3f8}code{background:#eef3f8;padding:2px 5px;overflow-wrap:anywhere}a{color:#08788e}</style>'+content+'</html>'
def build(mode):
    folder=DIST/('OpenFoamFriend_'+mode.upper()+'_'+BASE.name);folder.mkdir(parents=True,exist_ok=True)
    print('Staging',mode,flush=True)
    if not (folder/'runtime/python.exe').exists():shutil.copytree(CACHE/'portable_runtime',folder/'runtime',dirs_exist_ok=True,ignore=shutil.ignore_patterns('__pycache__'))
    # Place the wheel-supplied Microsoft C++ runtime beside CPython as well, so
    # direct VTK/Gmsh imports work before Qt without a system VC++ installation.
    for pattern in ('msvcp*.dll','vcruntime*.dll','concrt*.dll'):
        for library in (folder/'runtime/Lib/site-packages/PySide6').glob(pattern):shutil.copy2(library,folder/'runtime'/library.name)
    ssh=folder/'runtime/tools/openssh';ssh.mkdir(parents=True,exist_ok=True)
    for name in ('ssh.exe','scp.exe','sftp.exe','ssh-keygen.exe','ssh-keyscan.exe','ssh-add.exe','ssh-agent.exe','ssh-pkcs11-helper.exe','ssh-sk-helper.exe','libcrypto.dll','LICENSE.txt','NOTICE.txt'):
        shutil.copy2(CACHE/'ssh_client/OpenSSH-Win64'/name,ssh/name)
    app=folder/'application'/BASE.name
    shutil.copytree(BASE,app,dirs_exist_ok=True,ignore=shutil.ignore_patterns('data','evidence','__pycache__','dist','release_manifest.json','CONTINUE.md','HANDOFF.md'))
    shutil.copytree(BASE/'installer',folder/'installer',dirs_exist_ok=True,ignore=shutil.ignore_patterns('__pycache__','provision-linux.sh','clean-linux-image.sh','prepare_windows.ps1') if mode=='lite' else shutil.ignore_patterns('__pycache__'))
    if mode=='lite':
        # Remove Windows/Linux provisioning entrypoints from the application source copy too.
        for n in ('prepare_windows.ps1','provision-linux.sh','clean-linux-image.sh'):
            p=app/'installer'/n
            if p.exists():p.unlink()
        if (app/'install.ps1').exists():(app/'install.ps1').unlink()
    sources=json.loads((CACHE/'asset_sources.json').read_text());settings=dict(mode=mode,release=BASE.name,wsl_version='2.7.14.0',wsl_msi=sources['wsl']['file'],wsl_sha256=sources['wsl']['sha256'])
    sources['ssh']=json.loads((CACHE/'ssh_asset.json').read_text(encoding='utf-8-sig'))
    if mode=='full':
        payload=folder/'payload';payload.mkdir(exist_ok=True)
        for name in (settings['wsl_msi'],'openfoam14-ubuntu24.04.tar.gz'):shutil.copy2(CACHE/name,payload/name)
        settings['linux_image']=json.loads((CACHE/'clean_image.json').read_text())
    (folder/'bundle.json').write_text(json.dumps(settings,indent=2),encoding='utf-8')
    (folder/'asset_sources.json').write_text(json.dumps(sources,indent=2),encoding='utf-8')
    docs=folder/'docs';docs.mkdir(exist_ok=True)
    for lang in ('ZH','EN'):(docs/('installation_'+lang+'.html')).write_text(guide(lang),encoding='utf-8')
    verification=BASE/'evidence/package_QA/package_verification.html'
    if verification.exists():
        for p in verification.parent.iterdir():
            if p.suffix in ('.html','.png','.json'):shutil.copy2(p,docs/p.name)
    (folder/'Setup.cmd').write_text('@echo off\nsetlocal\nchcp 65001 >nul\n"%~dp0runtime\\python.exe" -X utf8 "%~dp0installer\\setup_gui.py"\nif errorlevel 1 pause\n',encoding='ascii')
    for name,exe in [('Start Portable.cmd','pythonw.exe'),('Start Console.cmd','python.exe')]:
        (folder/name).write_text('@echo off\nsetlocal\nchcp 65001 >nul\n"%~dp0runtime\\'+exe+'" -X utf8 "%~dp0application\\'+BASE.name+'\\app.py"\n'+('if errorlevel 1 pause\n' if exe=='python.exe' else ''),encoding='ascii')
    (folder/'Check Environment.cmd').write_text('@echo off\nsetlocal\nchcp 65001 >nul\n"%~dp0runtime\\python.exe" -X utf8 "%~dp0installer\\check_environment.py"\nset off_exit=%errorlevel%\npause\nexit /b %off_exit%\n',encoding='ascii')
    if (CACHE/'component_sources/sources.json').exists():shutil.copytree(CACHE/'component_sources',folder/'component_sources',dirs_exist_ok=True)
    (folder/'THIRD_PARTY_NOTICES.txt').write_text('Open Foam Friend: zongxuan & hanwen. Application source included; third-party components retain their own licenses.\nPython license: runtime/LICENSE.txt. Python wheel licenses: runtime/Lib/site-packages/*dist-info/licenses (or LICENSE/COPYING). Dynamic libraries may be replaced with compatible versions; this bundle makes no restriction on debugging modifications to LGPL libraries.\nGmsh: GPLv2+ with exception; https://gmsh.info/doc/texinfo/gmsh.html#License ; corresponding source https://gmsh.info/src/gmsh-4.15.2-source.tgz\nQt/PySide6: Qt LGPL/GPL license texts in PySide6-6.11.2.dist-info/licenses; corresponding sources https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-6.11.2-src/ and https://download.qt.io/official_releases/qt/6.11/6.11.2/ . No Qt libraries modified.\nVTK: BSD; NumPy/SciPy: BSD; Matplotlib: PSF-derived; Pillow: HPND. See distributed license texts for dependencies.\nFULL Linux: /usr/share/doc/*/copyright and /opt/openfoam14/COPYING; OpenFOAM corresponding source in /opt/openfoam14/src, https://github.com/OpenFOAM/OpenFOAM-14 and https://dl.openfoam.org/ubuntu ; Ubuntu archive sources https://archive.ubuntu.com/ubuntu/ . No OpenFOAM source modifications.\nMicrosoft WSL: original Microsoft MSI and license terms; https://github.com/microsoft/WSL . No Microsoft binary modifications.\nAll versions and origin hashes in asset_sources.json, bundle.json and bundle_manifest.json.\n',encoding='utf-8')
    with (folder/'THIRD_PARTY_NOTICES.txt').open('a',encoding='utf-8') as f:f.write('OpenSSH portable client: upstream Microsoft/PowerShell 10.0.0.0p2-Preview release, explicitly upstream preview. Client files only; no SSH server/service installation. BSD terms and notices in runtime/tools/openssh. Gmsh and PySide corresponding-source archives are included in component_sources.\n')
    manifest(folder);print('Staged',folder,flush=True);return folder
if __name__=='__main__':
    for mode in (sys.argv[1:] or ['full','lite']):build(mode)
