"""Guided real-mesh preparation. Predictions are explicitly approximate."""
import copy,math
from PySide6.QtWidgets import *
from .i18n import tr,text

METHODS=['Structured cylinder O-grid','Gmsh triangle / prism','Gmsh quadrilateral / prism','Gmsh tetrahedral','Structured partitioned box']
def recommended(project):
    if not project.shapes: return 'Structured partitioned box'
    if len(project.shapes)==1 and project.shapes[0]['kind']=='circle' and abs(project.shapes[0]['width']-project.shapes[0]['height'])<1e-10: return 'Structured cylinder O-grid'
    return 'Gmsh triangle / prism'
def spin(value,minimum=1e-10,maximum=1e8,integer=False):
    w=QSpinBox() if integer else QDoubleSpinBox()
    if not integer: w.setDecimals(12)
    w.setRange(int(minimum) if integer else minimum,int(maximum) if integer else maximum); w.setValue(value); return w

class MeshAssistant(QDialog):
    def __init__(self,project,parent=None):
        super().__init__(parent); self.source=copy.deepcopy(project); self.generate=False; self.setWindowTitle(tr('Automatic mesh assistant')); self.resize(940,800); outer=QVBoxLayout(self)
        title=QLabel(text('Geometry → Resolution → Refinement → Real mesh preview','几何检查 → 密度 → 加密 → 真实网格预览')); title.setStyleSheet('font-size:20px;font-weight:600;color:#155976'); outer.addWidget(title)
        scroll=QScrollArea(); scroll.setWidgetResizable(True); panel=QWidget(); body=QVBoxLayout(panel); scroll.setWidget(panel); outer.addWidget(scroll,1)
        geometry=QGroupBox(text('1  Geometry and method','1  几何与方法')); form=QFormLayout(geometry); self.method=QComboBox()
        for m in METHODS:
            if project.dimension==2 and m=='Gmsh tetrahedral': continue
            self.method.addItem(tr(m),m)
        self.method.setCurrentIndex(self.method.findData(recommended(project))); form.addRow(text('Recommended method','推荐方法'),self.method)
        self.geometry_note=QLabel(text(f'{project.dimension}D · {len(project.shapes)} solid obstacle(s). All dimensions are metres. Automatic settings do not replace quality checks.',f'{project.dimension}D · {len(project.shapes)} 个实体。尺寸单位为米；自动设置不能替代质量检查。')); self.geometry_note.setWordWrap(True); form.addRow(self.geometry_note); body.addWidget(geometry)
        resolution=QGroupBox(text('2  Resolution and smooth growth','2  密度与平滑增长')); f=QFormLayout(resolution)
        self.preset=QComboBox()
        for en,zh,val in [('Quick preview (~5k O-grid cells)','快速预览（O-grid 约 5 千）',0),('Balanced (~20k O-grid cells)','均衡（O-grid 约 2 万）',1),('Fine (~80k O-grid cells)','精细（O-grid 约 8 万）',2)]: self.preset.addItem(text(en,zh),val)
        f.addRow(text('Density preset','密度预设'),self.preset)
        self.radial=spin(20,2,2000,True); self.theta=spin(64,16,8000,True); self.nz=spin(project.spanwise if project.dimension==3 else 1,1,2000,True); self.R=spin(project.outer_radius); self.E=spin(project.grading,.01,1e4); self.size=spin(project.cell_size)
        for en,zh,w in [('Radial cells','径向单元数',self.radial),('Circumferential cells (multiple of 4)','圆周单元数（4 的倍数）',self.theta),('Spanwise layers','展向层数',self.nz),('O-grid outer radius / m','O-grid 外半径 / m',self.R),('Radial last/first width ratio','径向末格 / 首格比',self.E),('Unstructured background size / m','非结构背景尺寸 / m',self.size)]: f.addRow(text(en,zh),w)
        self.estimate=QLabel(); self.estimate.setWordWrap(True); f.addRow(self.estimate); body.addWidget(resolution)
        controls=QGroupBox(text('3  Local refinement controls','3  局部加密控制')); f=QFormLayout(controls)
        self.near=QCheckBox(text('Add smoothly blended near-body size region','添加平滑过渡的近体尺寸区域')); self.near.setChecked(True); self.wake=QCheckBox(text('Add downstream graded wake region','添加下游渐变尾流区域')); self.wake.setChecked(True)
        self.near_size=spin(.1); self.wake_size=spin(.2); self.wake_length=spin(6.); self.wake_ratio=spin(4.,.1,100.)
        f.addRow(self.near); f.addRow(text('Near-body target size / m','近体目标尺寸 / m'),self.near_size); f.addRow(self.wake); f.addRow(text('Wake start target size / m','尾流起点目标尺寸 / m'),self.wake_size); f.addRow(text('Wake length / m','尾流长度 / m'),self.wake_length); f.addRow(text('Downstream size ratio','下游尺寸渐变比'),self.wake_ratio)
        self.refine_note=QLabel(); self.refine_note.setWordWrap(True); f.addRow(self.refine_note); body.addWidget(controls)
        quality=QGroupBox(text('4  Quality gate','4  质量门槛')); f=QFormLayout(quality); self.skew=spin(project.skew_limit,.01,4.); self.angle=spin(project.nonortho_limit,1.,70.); self.smoothing=spin(max(project.smoothing,10),0,100,True)
        for en,zh,w in [('Maximum allowed skewness','允许最大偏斜度',self.skew),('Maximum non-orthogonality / °','最大非正交角 / °',self.angle),('Smoothing iterations','平滑迭代次数',self.smoothing)]: f.addRow(text(en,zh),w)
        note=QLabel(text('A failed quality gate blocks solving. The software never relaxes limits automatically. The preview is generated by blockMesh / Gmsh and checked by OpenFOAM, not an illustrative grid.', '质量不合格会阻止求解，软件不会自动放宽阈值。预览由 blockMesh / Gmsh 真实生成并由 OpenFOAM 检查，不是示意网格。')); note.setWordWrap(True); f.addRow(note); body.addWidget(quality)
        self.status=QLabel(); self.status.setWordWrap(True); outer.addWidget(self.status); buttons=QHBoxLayout()
        for en,zh,fn in [('Cancel','取消',self.reject),('Apply settings','应用设置',lambda:self.finish(False)),('Generate and check real preview','生成并检查真实预览',lambda:self.finish(True))]: b=QPushButton(text(en,zh)); b.clicked.connect(fn); buttons.addWidget(b)
        outer.addLayout(buttons); self.preset.currentIndexChanged.connect(self.use_preset); self.method.currentIndexChanged.connect(self.update_state)
        for w in (self.radial,self.theta,self.nz,self.R,self.E,self.size): w.valueChanged.connect(self.update_state)
        self.use_preset()
    def use_preset(self):
        k=self.preset.currentData(); D=self.source.shapes[0]['width'] if self.source.shapes else min(self.source.xmax-self.source.xmin,self.source.ymax-self.source.ymin)/10
        self.radial.setValue([20,40,80][k]); self.theta.setValue([64,128,256][k]); self.size.setValue(D*[1.,.5,.25][k]); self.near_size.setValue(D/[12,20,32][k]); self.wake_size.setValue(D/[5,8,12][k]); self.wake_length.setValue(6*D); self.update_state()
    def update_state(self,*args):
        method=self.method.currentData(); ogrid=method=='Structured cylinder O-grid'; gmsh=method.startswith('Gmsh')
        for w in (self.radial,self.theta,self.R,self.E): w.setEnabled(ogrid)
        self.size.setEnabled(not ogrid); self.nz.setEnabled(self.source.dimension==3 and method!='Gmsh tetrahedral')
        for w in (self.near,self.wake,self.near_size,self.wake_size,self.wake_length,self.wake_ratio): w.setEnabled(gmsh and bool(self.source.shapes))
        n=self.radial.value()*self.theta.value()*(self.nz.value() if self.source.dimension==3 else 1)
        g=self.E.value()**(1/max(1,self.radial.value()-1))
        self.estimate.setText(text(f'Exact O-grid planned count: {n:,} cells; adjacent radial growth ≈ {g:.4f}.',f'O-grid 计划精确单元数：{n:,}；径向相邻增长率约 {g:.4f}。') if ogrid else text('Target sizes control local resolution. Actual cell count and quality are reported after generation.','目标尺寸控制局部密度；生成后才报告实际单元数与质量。'))
        self.refine_note.setText(text('O-grid uses radial grading only. Local rectangular near-body/wake regions apply to the unstructured methods; select one to enable them.', 'O-grid 只采用径向渐变。矩形近体/尾流尺寸区域适用于非结构方法，选择相应方法即可启用。'))
    def project(self):
        p=copy.deepcopy(self.source); p.mesh_method=self.method.currentData(); p.radial=self.radial.value(); p.circumferential=self.theta.value(); p.spanwise=self.nz.value(); p.outer_radius=self.R.value(); p.grading=self.E.value(); p.cell_size=self.size.value(); p.skew_limit=self.skew.value(); p.nonortho_limit=self.angle.value(); p.smoothing=self.smoothing.value()
        if p.mesh_method.startswith('Gmsh') and p.shapes:
            # Preserve manual regions; append explicitly selected assistant controls.
            s=p.shapes[0]; D=max(s['width'],s['height']); x=s['x']; y=s['y']
            def region(x0,y0,x1,y1,size,direction,ratio):
                x0=max(x0,p.xmin); y0=max(y0,p.ymin); x1=min(x1,p.xmax); y1=min(y1,p.ymax)
                if x1>x0 and y1>y0:
                    r=dict(x=x0,y=y0,width=x1-x0,height=y1-y0,size=size,direction=direction,ratio=ratio)
                    if r not in p.regions: p.regions.append(r)
            if self.near.isChecked(): region(x-1.5*D,y-1.5*D,x+1.5*D,y+1.5*D,self.near_size.value(),'uniform',1.)
            if self.wake.isChecked(): region(x+D/2,y-D,x+D/2+self.wake_length.value(),y+D,self.wake_size.value(),'x+',self.wake_ratio.value())
        p.validate()
        if p.mesh_method=='Structured partitioned box' and p.shapes: raise ValueError(text('Structured partitioned box requires an obstacle-free domain. Use Gmsh or the cylinder O-grid.','结构分区矩形网格要求无障碍物流场，请选择 Gmsh 或圆柱 O-grid。'))
        if p.mesh_method!='Structured cylinder O-grid':
            for s in p.shapes:
                if s['x']-s['width']/2<=p.xmin or s['x']+s['width']/2>=p.xmax or s['y']-s['height']/2<=p.ymin or s['y']+s['height']/2>=p.ymax: raise ValueError(text('An obstacle touches or exceeds the domain. Set domain bounds first.','实体接触或超出流场，请先调整流场范围。'))
        return p
    def finish(self,generate):
        try: self.result_project=self.project(); self.generate=generate; self.accept()
        except Exception as e: self.status.setText(str(e))
