"""Native in-app actionable tutorials and geometry presets."""
from PySide6.QtWidgets import QDialog,QVBoxLayout,QHBoxLayout,QListWidget,QTextBrowser,QPushButton,QComboBox,QLabel
from .i18n import text
from .templates import examples

class TemplateDialog(QDialog):
    def __init__(self,parent):
        super().__init__(parent); self.setWindowTitle(text('Typical flow starters','典型流场起点')); self.resize(590,310); box=QVBoxLayout(self); self.selection=QComboBox()
        for key,label in examples(): self.selection.addItem(label,key)
        box.addWidget(self.selection); note=QLabel(text('Starter geometries with explicit dimensions and uniform inlet. These are not validated benchmark solutions. Multiple bodies share the cylinder wall patch and total force. The empty box is uniform through-flow, not a no-slip channel. The previous design is preserved in data/recovery before loading a starter.','带明确尺寸与均匀入口的起点，不是已验证基准解。多实体共用 cylinder 壁面与总力；空矩形是均匀穿流，不是无滑移通道。载入前会在 data/recovery 保留当前设计。')); note.setWordWrap(True); box.addWidget(note); row=QHBoxLayout(); cancel=QPushButton(text('Cancel','取消')); cancel.clicked.connect(self.reject); row.addWidget(cancel); apply=QPushButton(text('Load starter','载入模板')); apply.clicked.connect(self.accept); row.addWidget(apply); box.addLayout(row)

class Quickstart(QDialog):
    def __init__(self,parent):
        super().__init__(parent); self.setWindowTitle(text('Quick tutorials — actual workflow','快速教程 — 真实流程')); self.resize(900,600); box=QVBoxLayout(self); row=QHBoxLayout(); self.list=QListWidget(); self.browser=QTextBrowser(); row.addWidget(self.list,1); row.addWidget(self.browser,3); box.addLayout(row,1)
        topics=[(text('1 · Draw a closed solid','1 · 绘制闭合实体'),text('Design → Polygon solid. Click each vertex; Enter or right click closes it. Open Line/Polyline remain construction references. Circle: centre then radius point. Rectangle/triangle: two opposite bounding-box corners. Drag is still supported. Esc cancels. Self-intersections are rejected. Polygon solids switch incompatible default O-grid to Gmsh; geometry Undo also restores the earlier method.','设计 → 多边形实体。逐个点击顶点，Enter 或右键闭合。开放直线/折线仍为辅助线。圆：中心后半径点；矩形/三角形：包围盒两角。仍支持拖绘；Esc 取消，拒绝自交。实体会将不兼容的默认 O-grid 改为 Gmsh；撤销几何时同时恢复原网格方法。')),
        (text('2 · Grade and refine','2 · 渐变与加密'),text('Single-click Mesh operations → Refinement/spacing opens the editable page. Apply saves inputs; Generate/check makes the mesh. Meshing → Draw refinement region, then Mesh spacing. Uniform or x+/x-/y+/y- controls local size growth. O-grid uses radial simpleGrading; rectangular regions do not refine that topology. Gmsh uses blended background size fields. Structured partitioned box propagates subdivisions across blocks for conformity.','单击网格操作 → 加密/间距打开可编辑页。应用保存输入；生成/检查才生成网格。网格 → 绘制加密区域，再点网格间距。可选 uniform 或 x+/x-/y+/y- 渐变。O-grid 使用径向 simpleGrading，矩形区域不加密该拓扑。Gmsh 使用平滑背景尺寸场；分块矩形传播共享边划分以保持共形。')),
        (text('3 · Inspect all generated files','3 · 查看全部生成文件'),text('Files → Generated design files: builds actual 0/U, 0/p, turbulence fields, physicalProperties, momentumTransport, controlDict, fvSchemes, fvSolution and decomposeParDict. Structured methods also generate blockMeshDict. Gmsh generates geometry.msh and geometry.brep plus source snapshot. Draft is not a checked mesh. Select a queue case to inspect constant/polyMesh and real time fields read-only.','文件 → 生成设计文件：生成真实 0/U、0/p、湍流场、physicalProperties、momentumTransport、controlDict、fvSchemes、fvSolution、decomposeParDict。结构方法另有 blockMeshDict；Gmsh 有 geometry.msh、geometry.brep 和源码快照。草稿不等于已检查网格；选队列算例可只读查看 constant/polyMesh 与真实时间场。')),
        (text('4 · Manual blockMesh code','4 · 手动 blockMesh 代码'),text('Choose a structured method. Generated design files → system/blockMeshDict: edit vertices, blocks, arcs and grading, then Save draft & apply. This explicit override is used by actual blockMesh. It must still pass checkMesh. Remove the override explicitly before switching to Gmsh. Preprocessing → Manual topology adds node/curve/region drafting; general 3D CAD topology is not implemented.','选结构方法。生成设计文件 → system/blockMeshDict：编辑顶点、块、圆弧与渐变，保存草稿并应用。实际 blockMesh 使用该覆盖，仍须通过 checkMesh。改用 Gmsh 前须明确移除覆盖。前处理 → 手动拓扑支持节点/曲线/区域绘制；尚不支持任意三维 CAD 拓扑。')),
        (text('5 · Check, run and export','5 · 检查、运行、导出'),text('Meshing → Generate/check mesh. Inspect actual quality and worst faces in Scenes. Set physical model and reference scales, then Run queue → Submit design. Monitor actual Co, time and logs. Open result → field and time controls; export real .foam folder, MAT, CSV and GIF. Internal integration step differs from saved-frame interval.','网格 → 生成/检查网格；到场景看实测质量和最坏面。设置物理模型与参考尺度，再运行队列 → 提交设计。监测实际 Co、时间、日志。打开结果后使用场/时间控件，可导出真实 .foam 文件夹、MAT、CSV、GIF。内部积分步长不同于保存帧间隔。'))]
        topics.append((text('6 · Draw and assign actual manual regions','6 · 手绘并指派真实网格区域'),text('Preprocessing → Manual topology. Line uses two clicks, arc uses start/through/end, Polyline joins successive clicks. Split inserts a shared node into a line or arc; Erase deletes exactly one node-to-node segment. Closed faces are selectable regions. Assign mapped side counts and final/first spacing ratios, or Gmsh triangle/quad target sizes. Shared mapped-edge constraints propagate. Use this topology, then Generate/check actual mesh. Coordinates and lengths are metres. Four-edge mapped regions use blockMesh; split-sided or holed regions use Gmsh. Geometry, solver and export tools remain available.','前处理 → 手动拓扑。直线两次点击，圆弧为起点/过点/终点，连续折线依次点选。点处打断在线或弧上插入共享节点；擦除只删除两个节点间的一段。闭合面可选为区域。指派映射边单元数与末/首间距比，或 Gmsh 三角/四边形目标尺寸；共享映射边约束传播。点击将此拓扑用于网格，再生成/检查真实网格。坐标与长度单位米。四边映射区域用 blockMesh；拆边多边形或带孔区域用 Gmsh。原几何、求解和导出工具保留。')))
        topics.append((text('7 · Click model / PIMPLE / mesh-field-export','7 · 单击模型 / PIMPLE / 网格场导出'),text('Single-click either the branch or its summary under Physics continuum, Solver & stopping criteria, or Scenes & reports. Both open the same persistent property page. PIMPLE changes are applied to fvSolution; time/output to controlDict, ranks to decomposeParDict. Apply is fixed below the scrolling form. Unapplied drafts survive page/language changes. Result actions enable after real data loads. Double-click and Enter follow the same route. Existing code overrides must be reviewed before conflicting parameter changes.','单击物理连续体、求解器与停止条件、场景与报告的父项或摘要，均打开同一持久属性页。PIMPLE 修改对应 fvSolution，时间/输出对应 controlDict，进程对应 decomposeParDict。应用按钮固定在滚动表单下方；切页和切换语言保留未应用草稿。真实数据加载后才启用结果操作。双击和 Enter 使用相同入口；参数修改与显式代码覆盖冲突时须先核对。')))
        self.topics=topics
        for title,_ in topics: self.list.addItem(title)
        self.list.currentRowChanged.connect(lambda i:self.browser.setHtml('<h2>'+topics[i][0]+'</h2><p style="line-height:1.8">'+topics[i][1]+'</p>')); self.list.setCurrentRow(0)
        buttons=QHBoxLayout()
        for en,zh,fn in [('Typical starters','典型模板',parent.typical_flows),('Generated files','生成文件',parent.generated_files),('Application source','软件源码',parent.source_files)]:
            b=QPushButton(text(en,zh)); b.clicked.connect(fn); buttons.addWidget(b)
        box.addLayout(buttons)
